sudo: false
language: node_js
node_js:
  - "node"

addons:
  firefox: "latest-beta"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build && npm test && bash <(curl -s https://codecov.io/bash)